### ISSUE TITLE
一个想法，这个引擎可以为MHW做画质优化

### ISSUE THREAD

**Issue by Narugakuruga** [HalcyonAlcedo/LuaEngine#2]
REFramework好像有给崛起调整画质选项的预设lua框架，
大佬做的这个Lua引擎有异曲同工之妙，而MHW也是通过一些shadow，LOD，AO quality来调节画质的。
能不能找到那些画质设置，然后进一步拉高预设从而达到极高清的画面效果呢？
例子：阴影质量的“高”对大多数主流显卡完全没有压力，如果能增加一个“极高”可以让MHW画面更漂亮

**Comment by HalcyonAlcedo** [comment]
我没有找到详细的数值设定，这些参数在内存中只显示了挡位，比如阴影质量高并非是特定的数值，而是3档，超过3则会被刷回3，如果能找到详细的数值设定则有可能进行修改
