### ISSUE TITLE
在任务中调用Engine_Quest失败

### ISSUE THREAD

**Issue by YiyangWilliam** [HalcyonAlcedo/LuaEngine#4]
想搞一个跳过任务的mod，但是调用会报错，下面时是mod咋写的
```
function on_time()
    if engine.Quest:new().State == 2 and engine.keypad(36) then 
        local Data_Quest = engine.Quest:new()
        Data_Quest:setState(3)
    end
end
```

在任务中按下home键会报错
![屏幕截图 2024-01-18 223316](https://github.com/HalcyonAlcedo/LuaEngine/assets/52186336/4c034cf2-e337-46ff-afa3-f6c26ba22c73)
怀疑是基址有问题
![屏幕截图 2024-01-18 223404](https://github.com/HalcyonAlcedo/LuaEngine/assets/52186336/6efe6b52-9e54-44ff-9008-d84d47bcf34b)

**Comment by YiyangWilliam** [comment]
n站最新的ct表改这个数能修改任务状态
![image](https://github.com/HalcyonAlcedo/LuaEngine/assets/52186336/56702441-c3fa-4705-8753-f733e93817e0)

**Comment by YiyangWilliam** [comment]
破案，把这个函数写的跟前面一样就行了
![image](https://github.com/HalcyonAlcedo/LuaEngine/assets/52186336/c218d5e0-934a-4e13-8083-8d37485deda7)

**Comment by HalcyonAlcedo** [comment]
确实可能存在空指针的情况，我稍后加上
