### ISSUE TITLE
关于使用插件后键鼠与手柄的问题

### ISSUE THREAD

**Issue by MatrixLau** [HalcyonAlcedo/LuaEngine#6]
找到了插件会导致的一个问题就是：在电脑有键鼠有手柄的时候，进入游戏加载后，游戏就会变成只认手柄，无论键鼠怎么操作都没用，我一开始以为是steam的问题，后面才发现是lua插件的问题

**Comment by MatrixLau** [comment]
发现了具体是LuaEngineAudio的问题

**Comment by eigeen** [comment]
Audio用的旧版加载方案，可能产生了一定问题。我会检查一下Audio与当前版本的兼容性。

**Comment by HalcyonAlcedo** [comment]
问题已经解决。
